### ISSUE TITLE
Small fix + feature request

### ISSUE THREAD

**Issue by leodeleon22** [iondrimba/react-weather-app#76]
@iondrimba Congratulations for the great work
Do you think it’s possible to add the following changes:

- Rename **_Fry_** to _**Fri**_
- Make the design resizable
_Since the iPad doesn’t have a native weather app this would be a good alternative_

**Comment by iondrimba** [comment]
Hi @leodeleon22 thanks for the feedback. I will make that fix 👍

**Comment by iondrimba** [comment]
Feel free to contribute on that fix too if you feel confortable @leodeleon22 .
You can open a PR with that change 👍

**Comment by iondrimba** [comment]
Fix here https://github.com/iondrimba/react-weather-app/pull/78 @leodeleon22 
I'll let you know when is deployed. Thanks for the issue 🏅
